{
 "title": "Cardanow",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "query": "mainnet, preprod, preview" }
  ]
 },
 "panels": [
  {
   "title": "Seconds from last start: R2 bucket synchronization service",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "time() - cardanow_r2_bucket_sync_starts",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "$network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "network" },
  {
   "title": "Active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"cardanow-$network.service\", state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Seconds from last start: exporter service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "time() - cardanow_starts_$network",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Systemd logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{unit=\"cardanow-$network.service\"} |= ``"
    }
   ]
  }
 ]
}