version: "3.9"

services:
  cardano-node:
    image: inputoutput/cardano-node:8.1.2
    networks:
      - internal-network
    volumes:
      - ${MITHRIL_SNAPSHOTS_BASE_DIR}:${CONTAINER_DATA_DB_PATH}
      - ${LOCAL_CONFIG_PATH}:${CONTAINER_CONFIG_BASE_PATH}
      - type: volume
        source: cardano-node-ipc
        target: ${CONTAINER_IPC_PATH}
      - type: volume
        source: cardano-node-data
        target: ${CONTAINER_DATA_PATH}

    command:
      - "run"
      - "--config"
      - "${CONTAINER_CONFIG_CONFIG_PATH}"
      - "--topology"
      - "${CONTAINER_CONFIG_TOPOLOGY_PATH}"
      - "--database-path"
      - "${CONTAINER_DATA_DB_PATH}"
      - "--socket-path"
      - "${CONTAINER_SOCKET_PATH}"
  kupo:
    image: cardanosolutions/kupo:v2.7.0
    depends_on:
      cardano-node:
        condition: service_started
    volumes:
      - ${KUPO_DATA}:${CONTAINER_DATA_DB_PATH}
      - ${LOCAL_CONFIG_PATH}:${CONTAINER_CONFIG_BASE_PATH}
      - type: volume
        source: cardano-node-ipc
        target: ${CONTAINER_IPC_PATH}
    ports:
      - "1442:1442"
    command:
      - "--node-socket"
      - "${CONTAINER_SOCKET_PATH}"
      - "--node-config"
      - "${CONTAINER_CONFIG_CONFIG_PATH}"
      - "--defer-db-indexes"
      - "--host"
      - "0.0.0.0"
      - "--workdir"
      - "db"
      - "--since"
      - "origin"
      - "--match"
      - "*"

volumes:
  cardano-node-ipc:
  cardano-node-data:

networks:
  internal-network:
    internal: true
