services:
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:8.9.0
    networks:
      - internal-network
    volumes:
      - cardano-node-ipc:${CONTAINER_IPC_PATH}
      - ${LOCAL_MITHRIL_SNAPSHOT_DIR}:${CONTAINER_DATA_PATH}
      - ${LOCAL_CONFIG_PATH}:${CONTAINER_CONFIG_BASE_PATH}
    command:
      - "run"
      - "--config"
      - "${CONTAINER_CONFIG_CONFIG_PATH}"
      - "--topology"
      - "${CONTAINER_CONFIG_TOPOLOGY_PATH}"
      - "--database-path"
      - "${CONTAINER_DATA_DB_PATH}"
      - "--socket-path"
      - "${CONTAINER_SOCKET_PATH}"

  kupo:
    image: cardanosolutions/kupo:v2.8.0
    depends_on:
      cardano-node:
        condition: service_started
    volumes:
      - cardano-node-ipc:${CONTAINER_IPC_PATH}
      - ${LOCAL_KUPO_DATA_PER_SNAPSHOT}:${CONTAINER_KUPO_DB_PATH}
      - ${LOCAL_CONFIG_PATH}:${CONTAINER_CONFIG_BASE_PATH}
    ports:
      - "${KUPO_PORT}:1442"
    command:
      - "--node-socket"
      - "${CONTAINER_SOCKET_PATH}"
      - "--node-config"
      - "${CONTAINER_CONFIG_CONFIG_PATH}"
      - "--defer-db-indexes"
      - "--host"
      - "0.0.0.0"
      - "--workdir"
      - "${CONTAINER_KUPO_DB_PATH}"
      - "--since"
      - "origin"
      - "--match"
      - "*"

volumes:
  cardano-node-ipc:
  cardano-node-data:

networks:
  internal-network:
    internal: true
